@extends('layouts.app')
@section('title','Histórico do estoque • ETEFlow')
@section('page','chemical-stock-history')
@section('content')
<div class="app-shell">@include('operation.navigation')<main class="workspace"><header class="page-header"><div><span class="eyebrow">GESTÃO</span><h1>Histórico do estoque</h1><p>Contagens, entradas e divergências com autoria preservada.</p></div><a class="button secondary" href="{{ route('chemical-stock.dashboard') }}">Voltar ao estoque</a></header>@if(session('success'))<div class="success-alert">{{ session('success') }}</div>@endif @if($errors->any())<div class="form-alert">{{ $errors->first() }}</div>@endif
@foreach($counts as $count)<article class="panel-card"><div class="panel-head"><div><h2>Contagem • {{ $count->counted_at->format('d/m/Y H:i') }}</h2><p>{{ $count->user->name }} • turno #{{ $count->shift_id }}</p></div></div><div class="list">@foreach($count->items as $item)<div class="list-row"><div><b>{{ $item->product->name }} — {{ $item->location->name }}</b><small>Esperado: {{ $item->expected_quantity_snapshot??'—' }} • encontrado: {{ $item->quantity }} • diferença: {{ $item->difference_snapshot??'—' }} {{ $item->product->unit->symbol }}</small></div>@can('chemical_stock.correct')<details><summary>Corrigir</summary><form method="POST" action="{{ route('chemical-stock.corrections.store') }}" class="stack-form">@csrf<input type="hidden" name="record_type" value="COUNT_ITEM"><input type="hidden" name="record_id" value="{{ $item->id }}"><input type="hidden" name="idempotency_key" value="{{ (string) Illuminate\Support\Str::uuid() }}"><input type="number" name="corrected_quantity" min="0" step="any" required><input name="reason" placeholder="Justificativa" required><button class="button secondary">Registrar correção</button></form></details>@endcan</div>@endforeach</div></article>@endforeach
<article class="panel-card"><div class="panel-head"><div><h2>Movimentações</h2></div></div><div class="list">@foreach($movements as $movement)<div class="list-row"><div><b>{{ ['RECEIPT'=>'Entrada','ISSUE'=>'Retirada','TRANSFER'=>'Transferência','LOSS'=>'Perda','ADJUSTMENT'=>'Ajuste'][$movement->type]??$movement->type }} • {{ $movement->product->name }}</b><small>{{ $movement->quantity }} {{ $movement->product->unit->symbol }} • {{ $movement->source?->name??'—' }} → {{ $movement->destination?->name??'Uso operacional' }} • {{ $movement->creator->name }}</small></div><time>{{ $movement->occurred_at->format('d/m H:i') }}</time>@can('chemical_stock.correct')<details><summary>Corrigir</summary><form method="POST" action="{{ route('chemical-stock.corrections.store') }}" class="stack-form">@csrf<input type="hidden" name="record_type" value="MOVEMENT"><input type="hidden" name="record_id" value="{{ $movement->id }}"><input type="hidden" name="idempotency_key" value="{{ (string) Illuminate\Support\Str::uuid() }}"><input type="number" name="corrected_quantity" min="0" step="any" required><input name="reason" placeholder="Justificativa" required><button class="button secondary">Registrar correção</button></form></details>@endcan</div>@endforeach</div></article><article class="panel-card"><div class="panel-head"><div><h2>Inventários complementares</h2><p>Conferências específicas por produto/local.</p></div></div><div class="list">@forelse($inventories as $inventory)<div class="list-row"><div><b>{{ $inventory->product->name }} — {{ $inventory->location->name }}</b><small>Esperado {{ $inventory->expected_quantity }} • físico {{ $inventory->physical_quantity }} • diferença {{ $inventory->difference }} {{ $inventory->product->unit->symbol }} • {{ $inventory->checker->name }}@if($inventory->reason) • {{ $inventory->reason }}@endif</small></div><time>{{ $inventory->checked_at->format('d/m H:i') }}</time></div>@empty<div class="empty-state">Nenhum inventário complementar registrado.</div>@endforelse</div></article>
<article class="panel-card"><div class="panel-head"><div><h2>Sacos abertos e pesagens</h2><p>Rastreabilidade do polímero retirado para a UAP.</p></div></div><div class="list">@forelse($openPackages as $package)<details class="list-row"><summary><b>{{ $package->product->name }} • saco #{{ $package->id }}</b> — {{ $package->status==='OPEN'?'Em uso':'Finalizado' }} — {{ $package->remaining_content }} {{ $package->contentUnit->symbol }} restantes</summary><small>Aberto por {{ $package->opener->name }} em {{ $package->opened_at->format('d/m/Y H:i') }} • origem {{ $package->sourceLocation->name }}</small>@foreach($package->weighings as $weighing)<div class="list-row"><span>{{ $weighing->weighed_at->format('d/m H:i') }} • restante {{ $weighing->remaining }} {{ $package->contentUnit->symbol }} • consumido {{ $weighing->consumed }} {{ $package->contentUnit->symbol }}</span><small>{{ $weighing->weigher->name }}</small></div>@endforeach</details>@empty<div class="empty-state">Nenhum saco aberto registrado.</div>@endforelse</div></article></main></div>
@endsection
