@extends('layouts.app')
@section('title','Indicadores • ETEFlow')
@section('content')
<div class="app-shell">@include('operation.navigation')<main class="workspace indicators-workspace">
<header class="indicators-hero"><div><span class="eyebrow">BI OPERACIONAL</span><h1>{{ $unit->name }} <span>›</span> {{ $page?->name ?? 'Visão geral' }}</h1><p>Leituras e análises consolidadas do período selecionado.</p></div><div class="indicators-hero-actions"><span class="live-dot"><i></i> Dados atualizados</span>@can('indicators.configure')<a class="button secondary" href="{{ route('admin.indicators.index',['unit'=>$unit->id]) }}">Configurar</a>@endcan</div></header>
<form method="GET" class="indicator-filter-panel"><input type="hidden" name="unit" value="{{ $unit->id }}"><div class="filter-heading"><span>Filtros da análise</span><small>Escolha a página e o intervalo</small></div><label>Página<select name="page">@foreach($pages as $option)<option value="{{ $option->slug }}" @selected($page?->id===$option->id)>{{ $option->name }}</option>@endforeach</select></label><label>Data inicial<input type="date" name="from" value="{{ $from->format('Y-m-d') }}"></label><label>Data final<input type="date" name="to" value="{{ $to->format('Y-m-d') }}"></label><button class="button primary" type="submit">Atualizar painel</button></form>
<nav class="indicator-tabs" aria-label="Páginas do painel">@foreach($pages as $option)<a class="{{ $page?->id===$option->id?'active':'' }}" href="{{ route('indicators.index',['unit'=>$unit->id,'page'=>$option->slug,'from'=>$from->format('Y-m-d'),'to'=>$to->format('Y-m-d')]) }}">{{ $option->name }}</a>@endforeach</nav>
@php $ready=collect($cards)->where('state','READY'); $latest=$ready->pluck('last_data_at')->filter()->sortDesc()->first(); @endphp
<section class="indicator-overview"><article><span>Indicadores na página</span><strong>{{ count($cards) }}</strong><small>{{ $ready->count() }} com dados no período</small></article><article><span>Período analisado</span><strong>{{ $from->format('d/m') }} — {{ $to->format('d/m') }}</strong><small>{{ $to->diffInDays($from)+1 }} dias selecionados</small></article><article><span>Última atualização</span><strong>{{ $latest ? \Carbon\Carbon::parse($latest)->format('d/m H:i') : '—' }}</strong><small>registro mais recente</small></article></section>
<div class="indicator-section-title"><div><span class="eyebrow">PAINEL DE RESULTADOS</span><h2>{{ $page?->name ?? 'Visão geral' }}</h2></div><span class="period-pill">{{ $from->format('d/m/Y') }} até {{ $to->format('d/m/Y') }}</span></div>
<section class="indicator-grid">@forelse($cards as $card)<article class="panel-card indicator-card {{ $card['state']==='NO_DATA'?'is-empty':'' }}"><header class="indicator-card-head"><div><span class="indicator-source">{{ $card['indicator']['source_type']==='LAB_ANALYSIS'?'LABORATÓRIO':'OPERAÇÃO' }}</span><h3>{{ $card['indicator']['name'] }}</h3></div>@if($card['indicator']['unit'])<span class="unit-pill">{{ $card['indicator']['unit'] }}</span>@endif</header>@if($card['indicator']['description'])<p class="indicator-description">{{ $card['indicator']['description'] }}</p>@endif @if($card['state']==='NO_DATA')<div class="indicator-empty"><span>∅</span><b>Sem dados neste período</b><small>Altere o intervalo acima para consultar outros registros.</small></div>@elseif($card['indicator']['visualization']==='KPI')<div class="indicator-kpi-wrap"><strong class="indicator-kpi">{{ $card['value']===null?'—':number_format($card['value'],2,',','.') }}</strong><span>{{ $card['indicator']['unit'] ?: 'valor consolidado' }}</span></div>@if($card['last_data_at'])<small class="indicator-footer">Último registro em {{ \Carbon\Carbon::parse($card['last_data_at'])->format('d/m/Y H:i') }}</small>@endif @else<div class="indicator-chart" data-series='@json($card["series"])'><svg viewBox="0 0 600 220" role="img" aria-label="{{ $card['indicator']['name'] }}"></svg></div><footer class="indicator-footer"><span>{{ count($card['series']) }} registros</span><span>{{ $card['indicator']['aggregation']==='RAW'?'série temporal':'valor agregado' }}</span></footer>@endif</article>@empty<div class="indicator-empty-page"><span>▦</span><h2>Nenhum indicador nesta página</h2><p>Configure indicadores para começar a acompanhar os resultados.</p></div>@endforelse</section></main></div>
@endsection